const {chromium}=require(process.env.SORA_PLAYWRIGHT||'C:/Users/sanqi/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path');const out=path.resolve('runtime/guidelines_review');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true});const context=await browser.newContext({reducedMotion:'reduce'});await context.route('**/*',r=>new URL(r.request().url()).origin==='http://127.0.0.1:8100'?r.continue():r.abort());const page=await context.newPage();page.on('dialog',d=>d.accept());const results=[],errors=[];page.on('pageerror',e=>errors.push(e.message));const routes=process.env.AUDIT_VARIANTS?[...['/app/jobs/page','/app/job-batches/page','/app/library/page','/app/plaza/page','/app/quota/page','/admin/users/page','/admin/jobs/page','/admin/job-batches/page','/admin/reference-images/page','/admin/provider-keys/page','/admin/risk-control/page','/admin/quota-plans/page','/app/reference-images/page'].map(r=>r+'?state=empty'),...['/app/jobs/101/page','/admin/jobs/101/page'].flatMap(r=>['completed','failed'].map(s=>r+'?state='+s)),'/admin/jobs/page?batch_id=12','/app/library/page?state=empty&product_name=missing']:Object.keys(JSON.parse(fs.readFileSync('runtime/studio_preview/routes.json','utf8')));const configs=process.env.AUDIT_QUICK?[['light',1440]]:[['light',1440],['dark',1440],['light',390],['dark',390]];
async function scan(route,theme,width,state='page'){
 const axe=await page.evaluate(async()=>{const r=await window.axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21a','wcag21aa','best-practice']}});return {violations:r.violations.map(v=>({id:v.id,impact:v.impact,description:v.description,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary,html:n.html}))})),incomplete:r.incomplete.map(v=>({id:v.id,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}))};});
 const manual=await page.evaluate(()=>({missingDimensions:[...document.images].filter(e=>!e.hasAttribute('width')||!e.hasAttribute('height')).map(e=>e.outerHTML.slice(0,220)),noAutocomplete:[...document.querySelectorAll('input:not([type=hidden]):not([type=checkbox]):not([type=radio]),textarea')].filter(e=>!e.hasAttribute('autocomplete')).map(e=>e.name||e.id),themeColor:document.querySelector('meta[name=theme-color]')?.content||null,skip:!!document.querySelector('a[href="#main-content"]'),pageOverflow:document.documentElement.scrollWidth>innerWidth+2}));
 results.push({route,theme,width,state,...axe,manual});
}
for(const [theme,width] of configs){await page.setViewportSize({width,height:1000});await page.addInitScript(t=>localStorage.setItem('sora.theme',t),theme);for(const route of routes){await page.goto('http://127.0.0.1:8100'+route);await page.addScriptTag({path:'runtime/axe.min.js'});await scan(route,theme,width);if(process.env.AUDIT_STATES){for(const button of await page.locator('[data-open-drawer],[data-open-materials]').all()){if(!await button.isVisible())continue;await button.click();await scan(route,theme,width,'drawer');await page.keyboard.press('Escape');}for(const button of await page.locator('.tab-button').all()){await button.click();await scan(route,theme,width,'tab:'+await button.textContent());}}if(process.env.AUDIT_STATES){
  for(const selector of ['[data-account-toggle]','.wb-row-trigger','.plaza-open-btn','.usage-edit-btn','[data-show-register]']){const button=page.locator(selector).first();if(await button.isVisible()){await button.click();if(selector==='.plaza-open-btn')await page.locator('#plaza-modal:not(.hidden)').waitFor();await scan(route,theme,width,selector);await page.keyboard.press('Escape');}}
  if(width===390&&await page.locator('[data-open-nav]').isVisible()){await page.click('[data-open-nav]');await scan(route,theme,width,'mobile-nav');await page.keyboard.press('Escape');}
 }console.log(theme+' '+width+' '+route);}}
fs.writeFileSync(path.join(out,process.env.AUDIT_VARIANTS?'audit-variants.json':process.env.AUDIT_QUICK?'audit-initial.json':'audit-final.json'),JSON.stringify({results,errors},null,2));const customFailures=results.filter(r=>r.manual.missingDimensions.length||r.manual.noAutocomplete.length||!r.manual.skip||!r.manual.themeColor||r.manual.pageOverflow);const summary={customFailures,views:results.length,violationTypes:[...new Set(results.flatMap(r=>r.violations.map(v=>v.id)))],violationNodes:results.reduce((n,r)=>n+r.violations.reduce((m,v)=>m+v.nodes.length,0),0),errors};console.log(JSON.stringify(summary,null,2));await browser.close();if(summary.violationNodes||customFailures.length||errors.length)process.exitCode=1;})().catch(e=>{console.error(e);process.exit(1)});
