const {chromium}=require(process.env.SORA_PLAYWRIGHT||'C:/Users/sanqi/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs');
(async()=>{const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});page.on('dialog',d=>d.accept());const base='http://127.0.0.1:8101',out='design/mature/evidence';await page.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());const checks=[];
for(const theme of ['light','dark'])for(const [name,route]of [['login','/login'],['create','/app'],['detail','/app/jobs/101/page?state=completed'],['users','/admin/users/page'],['usage','/admin/usage/monthly/page']]){
 await page.addInitScript(t=>localStorage.setItem('sora.theme',t),theme);await page.setViewportSize({width:1440,height:1000});
 for(const before of [true,false]){await page.goto(base+(before?'/before':'')+route);if(name==='create'){await page.selectOption('#job-model-select','key:2:10');await page.fill('[name=product_name]','Lumora Studio');await page.fill('[name=region_name]','美国');await page.fill('[name=prompts]','雨夜城市，镜头缓慢推进。湿润的路面映出暖色灯光，路人撑伞经过，保持电影质感与自然景深。');await page.click('#add-prompt-btn');await page.locator('#prompt-list textarea').last().fill('以产品为视觉中心。柔和的侧光掠过玻璃，镜头从轮廓移动到细节，背景安静、干净。');await page.click('#add-prompt-btn');await page.locator('#prompt-list textarea').last().fill('自然光下的人物侧影，镜头缓缓拉远，保留环境与人物之间的呼吸感。');if(!before){for(const el of await page.locator('[data-collapse-prompt]').all())await el.click();}await page.click('[data-open-materials]');await page.locator('[data-preset-choice]').first().check();await page.click('#wb-apply-materials');await page.evaluate(()=>scrollTo(0,0));}await page.screenshot({path:`${out}/${before?'before':'after'}-${name}-${theme}.png`,fullPage:true});}
 await page.setViewportSize({width:720,height:500});await page.goto(base+route);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);checks.push({name,theme,probe:'200% equivalent layout viewport (1440 / 2)',overflow});
}
// Touch sizes are measured for principal mobile actions, including dialog footer buttons.
await page.setViewportSize({width:390,height:844});for(const route of ['/login','/app','/admin/users/page']){await page.goto(base+route);const sizes=await page.evaluate(()=>[...document.querySelectorAll('.primary-btn,.theme-icon-button,[data-open-nav],[data-open-materials],#add-prompt-btn')].filter(e=>e.getClientRects().length).map(e=>({label:e.getAttribute('aria-label')||e.textContent.trim(),width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height})));checks.push({route,probe:'principal mobile targets',sizes});}
fs.writeFileSync(out+'/additional.json',JSON.stringify(checks,null,2));await browser.close();console.log('Captured 20 before/after screenshots; 10 equivalent-zoom layouts and mobile targets');})();
