const {chromium}=require(process.env.SORA_PLAYWRIGHT||'C:/Users/sanqi/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1440,height:900},reducedMotion:'reduce',recordVideo:{dir:'design/mature/evidence/login-wall-motion',size:{width:1440,height:900}}}),page=await context.newPage();const base='http://127.0.0.1:8101',out='design/mature/evidence/login-wall';fs.mkdirSync(out,{recursive:true});const results=[],errors=[];await context.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
for(const theme of ['light','dark'])for(const [width,height]of [[375,812],[390,844],[768,1024],[1024,768],[1440,900],[1920,1080],[844,390],[720,450]]){await page.setViewportSize({width,height});await page.addInitScript(t=>localStorage.setItem('sora.theme',t),theme);await page.goto(base+'/login');await page.waitForFunction(()=>[...document.querySelectorAll('.lumora-wall-tile img')].every(e=>e.complete));const data=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth+1,broken:[...document.querySelectorAll('.lumora-wall-tile img')].filter(e=>!e.naturalWidth).length,panelWidth:document.querySelector('.wb-auth-form-region').getBoundingClientRect().width}));await page.addScriptTag({path:'runtime/axe.min.js'});const violations=await page.evaluate(async()=>{const r=await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21a','wcag21aa','best-practice']}});return r.violations.map(v=>({id:v.id,targets:v.nodes.map(n=>n.target)}));});results.push({theme,width,height,...data,violations});console.log(theme,width,data.overflow,violations.map(v=>v.id));if([390,1440].includes(width))await page.screenshot({path:`${out}/${theme}-${width}.png`,fullPage:true});}
await page.setViewportSize({width:1440,height:900});await page.emulateMedia({reducedMotion:'no-preference'});await page.goto(base+'/login');const order1=await page.locator('.lumora-wall-tile img').evaluateAll(es=>es.map(e=>e.getAttribute('src')).join('|'));await page.reload();const order2=await page.locator('.lumora-wall-tile img').evaluateAll(es=>es.map(e=>e.getAttribute('src')).join('|'));assert.notEqual(order1,order2);
const panel1=await page.locator('.wb-auth-form-region').boundingBox();await page.mouse.move(100,100);await page.waitForTimeout(760);const stage1=await page.locator('.lumora-wall-row').first().evaluate(e=>getComputedStyle(e).transform);await page.mouse.move(1340,800,{steps:12});await page.waitForTimeout(760);const stage2=await page.locator('.lumora-wall-row').first().evaluate(e=>getComputedStyle(e).transform),panel2=await page.locator('.wb-auth-form-region').boundingBox();assert.notEqual(stage1,stage2);const rowShifts=await page.locator('.lumora-wall-row').evaluateAll(es=>es.map(e=>new DOMMatrixReadOnly(getComputedStyle(e).transform).m41));assert(rowShifts[0]>0&&rowShifts[1]<0&&rowShifts[2]>0&&rowShifts[3]<0);await page.mouse.move(1340,100);await page.waitForTimeout(760);assert.equal(await page.locator('.lumora-wall-row').first().evaluate(e=>getComputedStyle(e).transform),stage2);assert.deepEqual(panel1,panel2);assert.equal(await page.locator('.lumora-wall-row').first().evaluate(e=>e.getAnimations().length),0);await page.emulateMedia({reducedMotion:'reduce'});await page.mouse.move(100,100);assert.equal(await page.locator('.lumora-wall-row').first().evaluate(e=>getComputedStyle(e).transform),'none');
await page.setViewportSize({width:390,height:844});await page.emulateMedia({reducedMotion:'no-preference'});await page.mouse.move(350,700);assert.equal(await page.locator('.lumora-wall-row').first().evaluate(e=>e.style.transform),'translate3d(0px, 0px, 0px)');
await page.goto(base+'/login?scenario=error');await page.fill('[name=username]','sample_user');await page.fill('[name=password]','fictional-only');await page.click('[data-login-form] button[type=submit]');await page.locator('[data-form-error]').waitFor();assert.equal(await page.inputValue('[name=username]'),'sample_user');await page.click('[data-show-register]');assert(await page.locator('[data-register-form]').isVisible());await page.keyboard.press('Tab');
await page.route('**/public-cover-*.webp',r=>r.abort());await page.goto(base+'/login');await page.waitForTimeout(150);assert(await page.locator('[data-login-form] button').isEnabled());assert.equal(await page.locator('.lumora-wall-tile img').evaluateAll(es=>es.filter(e=>e.complete&&!e.naturalWidth&&getComputedStyle(e).visibility!=='hidden').length),0);
const video=page.video();await context.close();await video.saveAs(out+'/motion.webm');await browser.close();const report={results,errors,behavior:{randomized:order1!==order2,stage1,stage2,panelStable:true,reducedMotion:true,mobileStatic:true,errorInputPreserved:true,registration:true,failedImagesDoNotBlock:true}};fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));if(errors.length||results.some(r=>r.overflow||r.broken||r.violations.length))process.exitCode=1;
})().catch(e=>{console.error(e);process.exit(1)});
