const {chromium}=require(process.env.SORA_PLAYWRIGHT||'C:/Users/sanqi/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{
const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'no-preference',permissions:['clipboard-read','clipboard-write'],recordVideo:{dir:'runtime/lumora_review/motion-v2',size:{width:1440,height:1000}}});const page=await context.newPage();page.on('dialog',dialog=>dialog.accept());const errors=[],results={};page.on('pageerror',e=>errors.push(e.message));await context.route('**/*',route=>new URL(route.request().url()).origin==='http://127.0.0.1:8100'?route.continue():route.abort());
await page.goto('http://127.0.0.1:8100/admin/users/page');
const start=await page.locator('.wb-stage').evaluate(e=>e.getBoundingClientRect().left);await page.locator('[data-collapse-nav]').dispatchEvent('click');await page.waitForTimeout(60);const mid=await page.locator('.wb-stage').evaluate(e=>e.getBoundingClientRect().left);assert(mid>64&&mid<start);const w=await page.locator('.wb-user-table').evaluate(e=>e.clientWidth);await page.waitForTimeout(240);assert.equal(await page.locator('.wb-user-table').evaluate(e=>e.clientWidth),w);for(let i=0;i<5;i++){await page.locator('[data-collapse-nav]').dispatchEvent('click');await page.waitForTimeout(30);}await page.waitForTimeout(260);assert.equal(await page.locator('.wb-stage').evaluate(e=>e.getBoundingClientRect().left),200);results.navigation={start,mid,tableWidth:w,rapidReverse:true};
const trigger=page.locator('.wb-row-trigger').first();await trigger.click();await page.waitForTimeout(50);const menu=page.locator('.wb-floating-menu').first();await page.keyboard.press('Escape');await page.waitForTimeout(35);const menuMid=await menu.evaluate(e=>({opacity:Number(getComputedStyle(e).opacity),display:getComputedStyle(e).display,inert:e.inert}));assert(menuMid.opacity>0&&menuMid.opacity<1);assert.equal(menuMid.inert,true);assert.equal(await trigger.evaluate(e=>e===document.activeElement),true);await trigger.click();assert.equal(await menu.evaluate(e=>e.inert),false);await page.keyboard.press('Escape');await page.waitForTimeout(150);assert.equal(await menu.isVisible(),false);results.menu=menuMid;
await page.goto('http://127.0.0.1:8100/app');const recent=page.locator('.wb-recent');await recent.locator('summary').dispatchEvent('click');await page.waitForTimeout(50);const recentMid=await recent.evaluate(e=>parseFloat(getComputedStyle(e,'::details-content').blockSize));await page.waitForTimeout(220);const recentEnd=await recent.evaluate(e=>parseFloat(getComputedStyle(e,'::details-content').blockSize));assert(recentMid>0&&recentMid<recentEnd);await recent.locator('summary').dispatchEvent('click');await page.waitForTimeout(40);const recentClose=await recent.evaluate(e=>parseFloat(getComputedStyle(e,'::details-content').blockSize));assert(recentClose>0&&recentClose<recentEnd);results.recent={recentMid,recentEnd,recentClose};
await page.setViewportSize({width:390,height:844});await page.click('[data-open-nav]');await page.waitForTimeout(260);await page.keyboard.press('Escape');assert.equal(await page.locator('.wb-mobile-nav-dialog .wb-sidebar').count(),1);await page.click('[data-open-nav]');await page.waitForTimeout(220);assert.equal(await page.locator('.wb-mobile-nav-dialog[open] .wb-sidebar').count(),1);await page.keyboard.press('Escape');await page.waitForTimeout(240);assert.equal(await page.locator('.wb-shell>.wb-sidebar').count(),1);assert.equal(await page.locator('[data-open-nav]').evaluate(e=>e===document.activeElement),true);results.mobileNavigation='exit retains content; reopen cancels cleanup; focus restored';
await page.setViewportSize({width:1440,height:1000});await page.goto('http://127.0.0.1:8100/app/plaza/page');const detail=page.locator('.plaza-open-btn').first();await detail.click();await page.waitForTimeout(220);await page.keyboard.press('Escape');await page.waitForTimeout(40);const modal=page.locator('#plaza-modal');const modalMid=await modal.evaluate(e=>({opacity:Number(getComputedStyle(e).opacity),inert:e.inert}));assert(modalMid.opacity>0&&modalMid.opacity<1);assert.equal(modalMid.inert,true);await detail.click();await page.waitForTimeout(230);assert.equal(await modal.evaluate(e=>e.inert),false);await page.keyboard.press('Escape');await page.waitForTimeout(200);assert.equal(await modal.isVisible(),false);results.mediaOverlay=modalMid;
await page.goto('http://127.0.0.1:8100/app/library/page');const copy=page.locator('[data-copy-text]').first();const original=await copy.textContent();await copy.click();await page.waitForTimeout(100);await copy.click();assert.equal(await copy.textContent(),'已复制');await page.waitForTimeout(1350);assert.equal(await copy.textContent(),original);results.repeatedCopy='restores original label';
await page.goto('http://127.0.0.1:8100/app/jobs/101/page');await page.locator('[data-tab-target=events]').dispatchEvent('click');await page.waitForTimeout(25);await page.emulateMedia({reducedMotion:'reduce'});await page.waitForTimeout(30);assert.equal(await page.locator('.tab-panel.active').evaluate(e=>e.getAnimations().length),0);await page.locator('[data-tab-target=prompt]').click();assert.equal(await page.locator('.tab-panel.active').evaluate(e=>e.getAnimations().length),0);results.reducedMotion='cancels running reveal and disables new motion';
await context.close();await browser.close();assert.deepEqual(errors,[]);fs.writeFileSync('runtime/lumora_review/motion-v2.json',JSON.stringify({passed:true,results,errors,limits:['Chromium simulated devices only; no physical touch-device test']},null,2));console.log(JSON.stringify({passed:true,results,errors}));
})().catch(error=>{console.error(error);process.exit(1)});
