const {chromium}=require('C:/Users/sanqi/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const b=await chromium.launch();try{fs.mkdirSync('runtime/plaza-player',{recursive:true});const p=await b.newPage({viewport:{width:1920,height:912}});const errors=[];p.on('pageerror',e=>errors.push(e.message));
const clips={};for(const [w,h] of [[360,640],[640,360]])clips[w<h?'portrait':'landscape']=Buffer.from(await p.evaluate(async([w,h])=>{const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d'),stream=c.captureStream(10),rec=new MediaRecorder(stream,{mimeType:'video/webm'}),chunks=[];rec.ondataavailable=e=>chunks.push(e.data);const ended=new Promise(r=>rec.onstop=r);rec.start();for(let i=0;i<10;i++){ctx.fillStyle=i%2?'#6655cc':'#223355';ctx.fillRect(0,0,w,h);await new Promise(r=>setTimeout(r,100));}rec.stop();await ended;stream.getTracks().forEach(t=>t.stop());return Array.from(new Uint8Array(await new Blob(chunks).arrayBuffer()));},[w,h]));
let orientation='portrait';await p.route('**/app/plaza/jobs/*',r=>r.fulfill({json:{creator:'测试创作者',product_name:'画幅验证',size:orientation==='portrait'?'720x1280':'1280x720',seconds:1,model:'test',prompt:'很长的提示词\n'.repeat(200),output_file:{id:9}}}));await p.route('**/app/files/9/stream',r=>r.fulfill({contentType:'video/webm',body:clips[orientation]}));
for(const viewport of [{width:1920,height:912},{width:1329,height:912},{width:390,height:844},{width:320,height:640}])for(orientation of ['portrait','landscape']){
 await p.setViewportSize(viewport);await p.goto('http://127.0.0.1:8129/app/plaza/page');await p.locator('.plaza-open-btn').first().click();await p.waitForFunction(()=>document.querySelector('#plaza-player').videoWidth>0);await p.waitForTimeout(220);
 const rect=await p.locator('#plaza-player').boundingBox(),wrap=await p.locator('#plaza-modal .player-wrap').boundingBox();const expected=orientation==='portrait'?9/16:16/9;
 assert.ok(Math.abs(rect.width/rect.height-expected)<.01,JSON.stringify(rect));assert.ok(Math.abs(rect.height-wrap.height)<1,'wrapper must not stretch to prompt height');assert.ok(rect.y>=0&&rect.y+rect.height<=viewport.height,'player must fit viewport');
 await p.locator('#plaza-player').evaluate(v=>v.play());await p.waitForFunction(()=>document.querySelector('#plaza-player').currentTime>.1);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await p.screenshot({path:`runtime/plaza-player/${viewport.width}-${orientation}.png`});await p.keyboard.press('Escape');await p.waitForTimeout(200);assert.equal(await p.locator('#plaza-player').getAttribute('src'),null);assert.equal(await p.locator('.plaza-open-btn').first().evaluate(e=>e===document.activeElement),true);
}
assert.deepEqual(errors,[]);console.log('PASS: actual portrait/landscape playback, long prompt, 1920/1329/390/320px, aspect and wrapper dimensions, viewport fit, close cleanup and focus return.');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
