const {chromium}=require(process.env.SORA_PLAYWRIGHT||'C:/Users/sanqi/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict');const base='http://127.0.0.1:8100',out='runtime/image_confirmation';fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true});const views=[],errors=[];
for(const theme of ['light','dark'])for(const width of [390,1440]){
 const context=await browser.newContext({viewport:{width,height:1000},hasTouch:width===390,isMobile:width===390,reducedMotion:'reduce'});await context.addInitScript(t=>localStorage.setItem('sora.theme',t),theme);const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 let posts=[],dimensionCalls=0;
 await context.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());
 await page.route('**/app/reference-image/dimensions?*',r=>{dimensionCalls++;return r.fulfill({status:400,contentType:'application/json',body:JSON.stringify({detail:'本机读取图片超时'})});});
 await page.route('**/app/jobs/batch',r=>{posts.push(r.request().postData());return r.fulfill({status:400,contentType:'application/json',body:JSON.stringify({detail:posts.at(-1).includes('name="confirmed_reference_image_urls"')?'模拟上游不可用：输入已保留':'图片链接无法读取或不是有效图片'})});});
 await page.goto(base+'/app');await page.selectOption('#job-model-select','key:2:10');await page.fill('[name=product_name]','APP');await page.fill('[name=region_name]','CN');await page.fill('[name=prompts]','Test prompt');await page.locator('#omni-material-card summary').click();const url=page.locator('[name=omni_reference_image_urls]').first(),confirm=page.locator('#omni-material-card [name=confirmed_reference_image_urls]').first();
 await url.fill('https://example.test/image.png');assert.equal(await confirm.isChecked(),false);
 async function submit(){await page.locator('#create-job-form [type=submit]').click();await page.locator('.confirm-dialog[open] .primary-btn').click();await page.locator('#studio-form-error:not(.hidden)').waitFor();}
 await submit();assert.equal(posts.length,1);assert.ok(!posts[0].includes('name="confirmed_reference_image_urls"'));
 await confirm.check();await submit();assert.equal(posts.length,2);assert.ok(posts[1].includes('name="confirmed_reference_image_urls"'));assert.equal(await url.inputValue(),'https://example.test/image.png');assert.equal(await confirm.isChecked(),true);
 await url.fill('https://example.test/changed.png');assert.equal(await confirm.isChecked(),false);await confirm.check();await page.click('#omni-add-image');const second=page.locator('[name=omni_reference_image_urls]').nth(1);await second.fill('https://example.test/second.png');assert.equal(await page.locator('#omni-material-card [name=confirmed_reference_image_urls]:checked').count(),1);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);await page.screenshot({path:`${out}/confirmation-${theme}-${width}.png`,fullPage:true});await page.addScriptTag({path:'runtime/axe.min.js'});assert.deepEqual(await page.evaluate(async()=>(await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21a','wcag21aa','best-practice']}})).violations.map(v=>v.id)),[]);
 await page.selectOption('#job-model-select','key:3:10');assert.equal(await page.locator('[name=confirmed_reference_image_urls]:checked').count(),0);
 await page.selectOption('#job-model-select','key:1:12');await page.locator('#standard-reference-field summary').click();await page.fill('#reference-image-url','https://example.test/standard.png');await page.locator('#reference-image-hint').filter({hasText:'超时'}).waitFor();const standard=page.locator('#standard-reference-field [name=confirmed_reference_image_urls]');await standard.check();await page.locator('#reference-image-hint').filter({hasText:'跳过'}).waitFor();const calls=dimensionCalls;await submit();assert.equal(dimensionCalls,calls);assert.ok(posts.at(-1).includes('name="confirmed_reference_image_urls"'));
 await standard.uncheck();await page.locator('#reference-image-hint').filter({hasText:'超时'}).waitFor();assert.ok(dimensionCalls>calls);views.push({theme,width,passed:true});await context.close();
}
assert.deepEqual(errors,[]);fs.writeFileSync(`${out}/report.json`,JSON.stringify({views,errors,passed:true},null,2));await browser.close();console.log(JSON.stringify({views:views.length,passed:true}));})().catch(e=>{console.error(e);process.exit(1)});
