const {chromium}=require(process.env.SORA_PLAYWRIGHT||'C:/Users/sanqi/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict');
const base='http://127.0.0.1:8101',out='design/mature/evidence';
(async()=>{const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});const page=await context.newPage();page.on('dialog',d=>d.accept());const results=[],errors=[];page.on('pageerror',e=>errors.push(e.message));await context.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());
 async function check(name,run){try{await run();results.push({name,passed:true});console.log('PASS',name);}catch(e){results.push({name,passed:false,error:e.message});console.log('FAIL',name,e.message.slice(0,300));await page.screenshot({path:out+'/failure-'+results.length+'.png'});}}
 const go=url=>page.goto(base+url);
 await check('compact prompt expands on focus, retains height on blur, manually collapses',async()=>{await go('/app');const input=page.locator('#prompt-list textarea').first();assert.equal((await input.boundingBox()).height,96);await input.focus();assert.equal((await input.boundingBox()).height,168);await page.locator('[name=product_name]').focus();assert.equal((await input.boundingBox()).height,168);await page.click('[data-collapse-prompt]');assert.equal((await input.boundingBox()).height,96);});
 await check('100 prompt import; reject 101 without truncation; last focus is clear of footer',async()=>{await go('/app');await page.click('#batch-import-toggle');await page.fill('#batch-import-textarea',Array.from({length:100},(_,i)=>'镜头 '+i).join('\n\n'));await page.click('#batch-import-apply');assert.equal(await page.locator('#prompt-list textarea').count(),100);await page.locator('#prompt-list textarea').last().focus();await page.waitForTimeout(100);const last=await page.locator('#prompt-list textarea').last().boundingBox(),footer=await page.locator('.wb-submit').boundingBox();assert(last.y>=56&&last.y+last.height<=footer.y+2,JSON.stringify({last,footer}));await page.click('#batch-import-toggle');await page.fill('#batch-import-textarea','额外的第 101 条');await page.click('#batch-import-apply');assert.equal(await page.locator('#prompt-list textarea').count(),100);assert.match(await page.locator('.app-toast-error').textContent(),/100/);});
 await check('material draft cancel/apply; natural names; Omni arbitrary aspect',async()=>{await go('/app');await page.selectOption('#job-model-select','key:2:10');await page.click('[data-open-materials]');await page.locator('[data-preset-choice]').first().check();await page.keyboard.press('Escape');assert.equal(await page.locator('.wb-selected-item').count(),0);await page.click('[data-open-materials]');const names=await page.locator('.wb-preset-choice strong').allTextContents();assert.deepEqual(names,[...names].sort(new Intl.Collator('zh-CN',{numeric:true,sensitivity:'base'}).compare));await page.locator('[data-preset-choice]').first().check();await page.click('#wb-apply-materials');assert.equal(await page.locator('.wb-selected-item').count(),1);assert.equal(await page.locator('#wb-material-drawer').evaluate(e=>e.open),false);});
 await check('login failure preserves username and presents specific error; retry enabled',async()=>{await go('/login?scenario=error');await page.fill('[name=username]','sample_creator');await page.fill('[name=password]','fictional-password');await page.click('[data-login-form] button[type=submit]');await page.locator('[data-form-error],.login-alert,.app-toast-error').first().waitFor();assert.equal(await page.inputValue('[name=username]'),'sample_creator');assert.equal(await page.locator('[data-login-form] button[type=submit]').isDisabled(),false);assert.match(await page.locator('body').innerText(),/模拟请求失败/);});
 await check('generation failure retains inputs and one request despite repeat click',async()=>{await go('/app');await page.selectOption('#job-model-select','key:2:10');await page.fill('[name=product_name]','失败后仍保留');await page.fill('[name=region_name]','美国');await page.fill('[name=prompts]','在自然光下缓慢推进镜头');await page.click('[data-open-materials]');await page.locator('[data-preset-choice]').first().check();await page.click('#wb-apply-materials');let requests=0;await page.route(base+'/app/jobs/batch',async r=>{requests++;await new Promise(resolve=>setTimeout(resolve,400));await r.fulfill({status:400,contentType:'application/json',body:JSON.stringify({detail:'模拟生成失败'})});});await page.click('.wb-submit button');await page.getByRole('button',{name:'确认生成',exact:true}).click();await page.locator('.wb-submit button').dispatchEvent('click');await page.waitForTimeout(600);assert.equal(requests,1);assert.equal(await page.inputValue('[name=product_name]'),'失败后仍保留');assert.equal(await page.inputValue('[name=prompts]'),'在自然光下缓慢推进镜头');assert.match(await page.locator('body').innerText(),/模拟生成失败/);await page.unroute(base+'/app/jobs/batch');});
 await check('user filters operate; failed drawer save retains values and Esc restores focus',async()=>{await go('/admin/users/page?q=operator');assert.equal(await page.locator('.wb-user-table tbody tr').count(),1);assert.match(await page.locator('.wb-user-table tbody').textContent(),/operator/);await go('/admin/users/page?scenario=error');const trigger=page.locator('[data-open-drawer]');await trigger.click();await page.fill('#wb-create-user-form [name=username]','sample_user');await page.fill('#wb-create-user-form [name=password]','fictional-only');await page.click('#wb-create-user-form button[type=submit]');await page.locator('#wb-create-user-form [data-form-error]').waitFor();assert.equal(await page.inputValue('#wb-create-user-form [name=username]'),'sample_user');await page.keyboard.press('Escape');assert(await trigger.evaluate(e=>document.activeElement===e));});
 await check('month lengths and subadmin report cannot expose adjusted markers or real counts',async()=>{for(const [month,count]of [['2026-02',28],['2028-02',29],['2026-04',30],['2026-07',31]]){await go('/admin/usage/monthly/page?month='+month);assert.equal(await page.locator('thead th[data-day]').count(),count);}await go('/admin/usage/monthly/page?role=sub_admin');assert.equal(await page.locator('.usage-edit-btn,.usage-override,.usage-adjusted,#usage-modal').count(),0);assert.doesNotMatch(await page.locator('.usage-table').innerText(),/真实|真\s\d/);});
 await check('detail remote ID and long model/error wrap; completed video stays intact',async()=>{await go('/app/jobs/101/page?state=completed');const before=await page.locator('#job-player').evaluate(e=>e);assert(await page.locator('#download-btn').isVisible());await page.locator('#job-remote').evaluate(e=>e.textContent='remote_'+('a'.repeat(300)));await page.locator('.wb-detail-fields dd').nth(1).evaluate(e=>e.textContent='VeryLongModel-'.repeat(20));for(const width of [390,768,1440]){await page.setViewportSize({width,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));const style=await page.locator('#job-player').evaluate(e=>({fit:getComputedStyle(e).objectFit,height:e.getBoundingClientRect().height}));assert.equal(style.fit,'contain');assert(style.height<=900*.65+1);}await page.click('[data-tab-target=events]');await page.click('[data-tab-target=prompt]');assert.equal(await page.locator('#job-player').count(),1);});
 await check('mobile navigation and material drawer restore focus with no horizontal overflow',async()=>{await page.setViewportSize({width:390,height:844});await go('/app');const trigger=page.locator('[data-open-nav]');await trigger.click();assert.equal(await page.locator('.wb-mobile-nav-dialog[open]').count(),1);await page.keyboard.press('Escape');assert(await trigger.evaluate(e=>document.activeElement===e));await page.click('[data-open-materials]');assert.equal(await page.evaluate(()=>document.activeElement.tagName),'BUTTON');await page.keyboard.press('Escape');assert(await page.locator('[data-open-materials]').evaluate(e=>document.activeElement===e));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));});
 await check('manual/system theme and refresh retain selection; browser theme-color follows',async()=>{await go('/login');await page.click('[data-theme-option=dark]');await page.reload();assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');assert.equal(await page.locator('meta[name=theme-color]').getAttribute('content'),'#151620');await page.click('[data-theme-option=system]');await page.emulateMedia({colorScheme:'light'});await page.waitForFunction(()=>document.documentElement.dataset.theme==='light');assert.equal(await page.locator('html').getAttribute('data-theme'),'light');await page.emulateMedia({colorScheme:'dark'});await page.waitForFunction(()=>document.documentElement.dataset.theme==='dark');assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');});
 fs.writeFileSync(out+'/interactions.json',JSON.stringify({results,errors},null,2));await browser.close();if(results.some(r=>!r.passed)||errors.length)process.exitCode=1;
})();
