const {chromium}=require(process.env.SORA_PLAYWRIGHT||'C:/Users/sanqi/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');const base='http://127.0.0.1:8100',out=path.resolve('runtime/studio_review');
(async()=>{const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});page.on('dialog',dialog=>dialog.accept());const results=[],resourceFailures=[];page.on('response',r=>{if(r.status()>=400)resourceFailures.push({url:r.url(),status:r.status()});});
async function theme(t){await page.evaluate(t=>{localStorage.setItem('sora.theme',t);document.querySelectorAll('[data-theme-select]').forEach(el=>{el.value=t;el.dispatchEvent(new Event('change'));});},t);}
for(const state of ['completed','failed'])for(const t of ['light','dark'])for(const width of [375,390,768,1024,1440,1920]){
 await page.setViewportSize({width,height:1000});await page.goto(base+'/app/jobs/101/page?state='+state);await theme(t);await page.locator('#job-status').filter({hasText:state==='completed'?'已完成':'失败'}).waitFor();
 assert.equal(await page.locator('#download-btn').isVisible(),state==='completed');
 const fields=await page.locator('.wb-detail-fields dd').evaluateAll(nodes=>nodes.map(e=>({width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height})));assert(fields.every(f=>f.width>=140&&f.height<150));
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);
 if(state==='completed') {await page.locator('#job-player').evaluate(v=>v.play());await page.waitForFunction(()=>document.getElementById('job-player').currentTime>0);await page.locator('#job-player').evaluate(v=>v.pause());}
 if([390,1440].includes(width))await page.screenshot({path:path.join(out,`detail-${state}-${t}-${width}.png`),fullPage:true});
 results.push({state,theme:t,width,passed:true});
}
await page.setViewportSize({width:1440,height:1000});await page.goto(base+'/app');await theme('dark');await page.selectOption('#job-model-select','key:2:10');await page.fill('[name=product_name]','NiceReels');await page.fill('[name=region_name]','美国');await page.fill('[name=batch_name]','秋日品牌短片');await page.click('[data-open-materials]');await page.locator('[data-preset-choice]').first().check();await page.locator('[data-preset-choice]').nth(1).check();
// Native modal trap: last control cycles to the first and Escape restores origin.
await page.locator('#wb-apply-materials').focus();await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.closest('dialog')?.id),'wb-material-drawer');
await page.click('#wb-apply-materials');await page.fill('[name=prompts]','清晨的城市街道，镜头从玻璃橱窗缓缓推进。暖光落在产品表面，路人的剪影轻轻掠过。自然、安静的电影质感。');await page.click('#add-prompt-btn');await page.locator('[name=prompts]').nth(1).fill('沿产品金属边缘平稳移动，捕捉细腻纹理与柔和反射。背景简洁，浅景深，结尾停留在品牌细节。');
for(const t of ['dark','light']){await theme(t);await page.screenshot({path:path.join(out,`creator-filled-${t}-1440.png`),fullPage:true});}
await page.click('[data-open-materials]');await page.screenshot({path:path.join(out,'materials-drawer-light-1440.png'),fullPage:true});await page.keyboard.press('Escape');
// Boundary: append to exactly 100, reject one more, preserve input when quota is insufficient.
await page.click('#batch-import-toggle');await page.fill('#batch-import-textarea',Array(98).fill('边界提示词').join('\n\n'));await page.click('#batch-import-apply');assert.equal(await page.locator('[name=prompts]').count(),100);await page.click('.toast-dismiss');assert.equal(await page.locator('#add-prompt-btn').isDisabled(),true);await page.click('#batch-import-toggle');await page.fill('#batch-import-textarea','第 101 条');await page.click('#batch-import-apply');assert.equal(await page.locator('[name=prompts]').count(),100);await page.click('.toast-dismiss');await page.locator('#create-job-form button[type=submit]').click();await page.locator('#studio-form-error').filter({hasText:'额度不足'}).waitFor();assert.equal(await page.locator('[name=prompts]').count(),100);
// Simulate the effective CSS viewport at 200% browser zoom, plus a font scaling stress pass.
for(const route of ['/login','/app','/app/jobs/101/page','/admin/users/page']){
 await page.setViewportSize({width:720,height:500});await page.goto(base+route);await page.evaluate(()=>document.body.style.zoom='2');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);results.push({route,zoom:'CSS 200%, 720px viewport',passed:true});
}
await page.setViewportSize({width:844,height:390});await page.goto(base+'/login');await page.locator('[data-login-form] button[type=submit]').scrollIntoViewIfNeeded();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);results.push({orientation:'landscape 844x390',passed:true});
await page.setViewportSize({width:390,height:844});await page.goto(base+'/app');const targets=await page.locator('[data-open-nav],[data-open-materials],#add-prompt-btn,#create-job-form button[type=submit]').evaluateAll(nodes=>nodes.map(e=>({label:e.textContent||e.getAttribute('aria-label'),w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height})));assert(targets.every(t=>t.w>=44&&t.h>=44));
// Drive the actual theme control and verify system changes propagate.
await page.locator('[data-account-toggle]').click();await page.click('[data-theme-option=system]');await page.emulateMedia({colorScheme:'dark'});await page.waitForFunction(()=>document.documentElement.dataset.theme==='dark');assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');await page.emulateMedia({colorScheme:'light'});await page.waitForFunction(()=>document.documentElement.dataset.theme==='light');assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
fs.writeFileSync(path.join(out,'quality-report.json'),JSON.stringify({checks:results.length,results,targets,resourceFailures,limits:['CSS zoom stress is not a real browser zoom control','No physical touch-device check']},null,2));console.log(JSON.stringify({checks:results.length,resourceFailures,targets},null,2));await browser.close();assert.equal(resourceFailures.length,0);
})().catch(e=>{console.error(e);process.exit(1)});
