const {chromium}=require(process.env.SORA_PLAYWRIGHT||'C:/Users/sanqi/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true});const context=await browser.newContext({reducedMotion:'reduce'});await context.route('**/*',r=>new URL(r.request().url()).origin==='http://127.0.0.1:8100'?r.continue():r.abort());const page=await context.newPage();page.on('dialog',d=>d.accept());const views=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
for(const theme of ['light','dark'])for(const width of [390,768,1440,1920]){
 await page.setViewportSize({width,height:1000});await page.addInitScript(t=>localStorage.setItem('sora.theme',t),theme);await page.goto('http://127.0.0.1:8100/admin/usage/monthly/page');
 assert.equal(await page.locator('.usage-edit-btn').count(),720);assert.equal(await page.locator('thead [data-day]').count(),30);
 const geometry=await page.evaluate(()=>{const table=document.querySelector('.usage-table'),wrap=document.querySelector('.usage-table-wrap'),card=document.querySelector('.usage-report-card'),metrics=document.querySelector('.report-metrics'),parent=card.parentElement,style=getComputedStyle(parent),days=[...table.querySelectorAll('thead [data-day]')].map(el=>el.getBoundingClientRect().width);return {overflow:document.documentElement.scrollWidth>innerWidth+2,table:table.getBoundingClientRect().width,container:wrap.clientWidth,card:card.getBoundingClientRect().width,metrics:metrics.getBoundingClientRect().width,available:parent.clientWidth-parseFloat(style.paddingLeft)-parseFloat(style.paddingRight),user:table.querySelector('thead .usage-user').getBoundingClientRect().width,total:table.querySelector('thead .usage-month-total').getBoundingClientRect().width,day:days[0],daySpread:Math.max(...days)-Math.min(...days),button:table.querySelector('.usage-edit-btn').getBoundingClientRect().height};});
 assert.equal(geometry.overflow,false);assert.ok(Math.abs(geometry.card-geometry.available)<=2,JSON.stringify(geometry));assert.ok(Math.abs(geometry.metrics-geometry.available)<=2);assert.ok(geometry.daySpread<1);assert.ok(Math.abs(geometry.user-(width<768?124:148))<1);assert.ok(Math.abs(geometry.total-(width<768?64:68))<1);
 if(width>=1440){assert.ok(Math.abs(geometry.table-geometry.container)<=2);assert.ok(Math.abs(geometry.day-(geometry.container-geometry.user-geometry.total)/30)<1);}
 if(width===390){assert.ok(geometry.day>=44&&geometry.button>=44);assert.ok(geometry.table>geometry.container);await page.click('[data-usage-scroll="1"]');assert.ok(await page.locator('.usage-table-wrap').evaluate(el=>el.scrollLeft>0));}
 await page.screenshot({path:`runtime/guidelines_review/usage-${theme}-${width}.png`,fullPage:true});
 await page.addScriptTag({path:'runtime/axe.min.js'});const violations=await page.evaluate(async()=>(await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21a','wcag21aa','best-practice']}})).violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})));assert.deepEqual(violations,[]);views.push({theme,width,...geometry});
}
// Available width must be reclaimed when the navigation collapses, without reloading.
await page.setViewportSize({width:1440,height:1000});await page.goto('http://127.0.0.1:8100/admin/usage/monthly/page?month=2026-05');const before=(await page.locator('.usage-table').boundingBox()).width;await page.click('[data-collapse-nav]');await page.waitForFunction(w=>document.querySelector('.usage-table').getBoundingClientRect().width>w+100,before);assert.equal(await page.locator('thead [data-day]').count(),31);await page.click('[data-collapse-nav]');
await page.setViewportSize({width:1440,height:1000});await page.goto('http://127.0.0.1:8100/admin/usage/monthly/page?scenario=error');const first=page.locator('.usage-edit-btn').first();await first.focus();await page.keyboard.press('ArrowRight');assert.equal(await page.evaluate(()=>document.activeElement.dataset.date),'2026-06-02');await page.keyboard.press('ArrowDown');assert.equal(await page.evaluate(()=>document.activeElement.dataset.userId),'3');await page.keyboard.press('Control+End');
const sticky=await page.evaluate(()=>{const wrap=document.querySelector('.usage-table-wrap').getBoundingClientRect(),a=document.activeElement.getBoundingClientRect(),header=document.querySelector('.usage-table thead th').getBoundingClientRect(),user=document.querySelector('.usage-table tbody tr:last-child .usage-user').getBoundingClientRect();return {wrap,a,header,user};});assert.ok(sticky.a.top>=sticky.header.bottom&&sticky.a.bottom<=sticky.wrap.bottom+2);assert.ok(sticky.a.left>=sticky.user.right);
await page.keyboard.press('Enter');await page.locator('#usage-modal:not(.hidden)').waitFor();assert.equal(await page.inputValue('#usage-date'),'2026-06-30');await page.fill('#usage-display','77');await page.locator('#usage-modal form').first().locator('[type=submit]').click();await page.locator('#usage-modal [data-form-error]').waitFor();assert.equal(await page.inputValue('#usage-display'),'77');await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.activeElement.dataset.date),'2026-06-30');
// Large numbers must widen columns, never silently clip a usage count.
await page.addInitScript(()=>document.addEventListener('DOMContentLoaded',()=>{const cell=document.querySelector('.usage-edit-btn');if(cell)cell.textContent='999999';}));await page.goto('http://127.0.0.1:8100/admin/usage/monthly/page');assert.ok((await page.locator('thead [data-day]').first().boundingBox()).width>=46);
for(const width of [390,1440]){await page.setViewportSize({width,height:1000});await page.goto('http://127.0.0.1:8100/admin/rankings/page');assert.equal(await page.locator('.rankings-table tbody tr').count(),24);assert.equal(await page.locator('.rankings-table tbody tr:first-child td:nth-child(5)').textContent().then(t=>t.trim().length>0),true);assert.ok((await page.locator('.rankings-panel').boundingBox()).width<=940);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);await page.screenshot({path:`runtime/guidelines_review/rankings-${width}.png`,fullPage:true});}
await page.addInitScript(()=>document.addEventListener('DOMContentLoaded',()=>{const table=document.querySelector('.usage-table');if(!table)return;const body=table.tBodies[0],sample=body.querySelector('tr:not(.usage-total-row)');if(!sample)return;while(body.rows.length<81){const row=sample.cloneNode(true);row.querySelector('.usage-user strong').textContent='VeryLongAccountName'.repeat(8);body.append(row);}table.dataset.month='2026-05';table.style.setProperty('--usage-days','31');const head=table.querySelector('thead tr'),day=head.lastElementChild.cloneNode(true);day.dataset.day='31';head.append(day);table.querySelector('colgroup').append(table.querySelector('colgroup').lastElementChild.cloneNode(true));for(const row of body.rows)row.append(row.lastElementChild.cloneNode(true));}));
await page.setViewportSize({width:1440,height:1000});await page.goto('http://127.0.0.1:8100/admin/usage/monthly/page');assert.equal(await page.locator('.usage-edit-btn').count(),2480);assert.equal(await page.locator('.usage-table tbody.wb-large-list').count(),1);await page.locator('.usage-edit-btn').last().focus();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);assert.equal(await page.locator('.usage-total-row').evaluate(el=>getComputedStyle(el).contentVisibility),'visible');
assert.deepEqual(errors,[]);fs.writeFileSync('runtime/guidelines_review/reports-matrix.json',JSON.stringify({views,sticky,errors,passed:true,checks:['24 users × 30 days','full workspace width and evenly distributed dates','sidebar resize without reload','mobile horizontal paging','sticky headers and identity','arrow-key navigation','failed save preserves input','modal focus returns to exact day','large counts widen cells','compact rankings with complete fields','80 users × 31 days with long names']},null,2));console.log(JSON.stringify({views:views.length,passed:true}));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
