const {chromium}=require(process.env.SORA_PLAYWRIGHT||'C:/Users/sanqi/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const fs=require('node:fs'),assert=require('node:assert/strict');
function lum(c){return c.match(/[\d.]+/g).slice(0,3).map(Number).map(x=>x/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4).reduce((s,x,i)=>s+x*[.2126,.7152,.0722][i],0);}
function ratio(a,b){a=lum(a);b=lum(b);return (Math.max(a,b)+.05)/(Math.min(a,b)+.05);}
(async()=>{const b=await chromium.launch();const p=await b.newPage({viewport:{width:1440,height:1000},colorScheme:'dark',reducedMotion:'reduce'});const boundaries=[],switches=[];
await p.addInitScript(()=>{window.initialThemes=[];new MutationObserver(()=>{const value=document.documentElement?.dataset.theme;if(value&&window.initialThemes.at(-1)!==value)window.initialThemes.push(value);}).observe(document,{subtree:true,attributes:true,attributeFilter:['data-theme']});});
await p.goto('http://127.0.0.1:8100/login');
async function expected(theme){await p.waitForFunction(t=>document.documentElement.dataset.theme===t,theme);assert.equal((await p.locator('meta[name=theme-color]').getAttribute('content')).toLowerCase(),theme==='dark'?'#141827':'#f1f3fa');assert.equal(await p.evaluate(()=>document.documentElement.style.colorScheme),theme);switches.push(theme);}
await expected('dark');await p.click('[data-theme-option=light]');await expected('light');await p.reload();await expected('light');assert.deepEqual(await p.evaluate(()=>initialThemes),['light']);await p.click('[data-theme-option=system]');await expected('dark');await p.emulateMedia({colorScheme:'light'});await expected('light');await p.emulateMedia({colorScheme:'dark'});await expected('dark');await p.click('[data-theme-option=dark]');await p.emulateMedia({colorScheme:'light'});await expected('dark');await p.reload();await expected('dark');assert.deepEqual(await p.evaluate(()=>initialThemes),['dark']);
for(const theme of ['light','dark']){await p.evaluate(t=>localStorage.setItem('sora.theme',t),theme);for(const route of ['/login','/app','/admin/users/page','/admin/settings/page']){await p.goto('http://127.0.0.1:8100'+route);const records=await p.evaluate(()=>[...document.querySelectorAll('input:not([type=hidden]):not([type=checkbox]):not([type=radio]),select,textarea,.secondary-btn,.wb-add-material')].filter(e=>e.checkVisibility()&&!e.disabled).map(e=>{const owner=e.matches('.prompt-card textarea')?e.closest('.prompt-card'):e;const s=getComputedStyle(owner);let background=s.backgroundColor;for(let el=owner.parentElement;background==='rgba(0, 0, 0, 0)'&&el;el=el.parentElement)background=getComputedStyle(el).backgroundColor;return {name:e.name||e.className,border:s.borderTopColor,width:parseFloat(s.borderTopWidth),background};}));for(const record of records){if(!record.width)continue;const contrast=ratio(record.border,record.background);boundaries.push({theme,route,...record,contrast});assert.ok(contrast>=3,JSON.stringify(boundaries.at(-1)));}}}
fs.mkdirSync('runtime/palette_review',{recursive:true});fs.writeFileSync('runtime/palette_review/palette-check.json',JSON.stringify({switches,boundaries,passed:true},null,2));console.log(JSON.stringify({switchChecks:switches.length,boundaries:boundaries.length,minimumBoundary:Math.min(...boundaries.map(x=>x.contrast)),passed:true}));await b.close();})().catch(e=>{console.error(e);process.exit(1)});
