const {chromium}=require(process.env.SORA_PLAYWRIGHT||'C:/Users/sanqi/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch();try{
 const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),base='http://127.0.0.1:8101',results=[],errors=[];
 await page.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+'/design?page=login&revision=glass-2');await page.frameLocator('#new').locator('[data-login-form]').waitFor();assert.equal(await page.locator('[data-review-page=login]').getAttribute('aria-pressed'),'true');results.push('direct login page selection');
 for(const [name,selector] of [['create','#prompt-list textarea'],['detail','#job-player'],['users','.wb-user-directory'],['usage','.usage-table'],['login','[data-login-form]']]){await page.click('[data-review-page='+name+']');await page.frameLocator('#new').locator(selector).first().waitFor();assert(new URL(page.url()).searchParams.get('page')===name);results.push('page tab '+name);}
 await page.reload();await page.frameLocator('#new').locator('[data-login-form]').waitFor();results.push('login selection survives refresh');
 await page.click('#compare');await page.frameLocator('#old').locator('body').waitFor();assert(await page.locator('#baseline').isVisible());await page.click('#compare');
 await page.route(base+'/app',r=>r.abort());await page.click('[data-review-page=create]');await page.locator('#review-error').waitFor({state:'visible'});await page.unroute(base+'/app');await page.click('#retry-preview');await page.frameLocator('#new').locator('#prompt-list textarea').nth(2).waitFor();assert(await page.locator('#review-error').isHidden());results.push('unavailable preview feedback and retry');
 await page.selectOption('#theme','dark');await page.waitForFunction(()=>document.querySelector('#new').contentDocument.documentElement.dataset.theme==='dark');await page.selectOption('#theme','light');await page.waitForFunction(()=>document.querySelector('#new').contentDocument.documentElement.dataset.theme==='light');await page.screenshot({path:'design/mature/evidence/glass-2-review.png'});
 for(const theme of ['light','dark']){
  await page.selectOption('#theme',theme);await page.waitForTimeout(80);await page.locator('#new').screenshot({path:'design/mature/evidence/glass-2-workspace-'+theme+'.png'});
 }
 await page.goto(base+'/app');await page.locator('.wb-topbar [data-theme-option=light]').click();await page.reload();assert.equal(await page.locator('html').getAttribute('data-theme'),'light');await page.click('.wb-topbar [data-theme-option=dark]');assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');results.push('top bar icon themes and persistence');
 await page.fill('[name=prompts]','可复制、删除与收起的提示词');await page.click('#add-prompt-btn');assert.deepEqual(await page.locator('.prompt-card-head strong').evaluateAll(es=>es.map(e=>e.dataset.promptNumber)),['01','02']);await page.locator('[data-copy-prompt]').first().click();assert.equal(await page.locator('#prompt-list textarea').count(),3);await page.locator('[data-remove-prompt]').first().click();assert.deepEqual(await page.locator('.prompt-card-head strong').evaluateAll(es=>es.map(e=>e.dataset.promptNumber)),['01','02']);await page.locator('#prompt-list textarea').first().fill('继续编辑后编号仍然正确');assert.deepEqual(await page.locator('.prompt-card-head strong').evaluateAll(es=>es.map(e=>e.dataset.promptNumber)),['01','02']);results.push('icon prompt actions and sequential numbers');
 await page.setViewportSize({width:375,height:812});await page.goto(base+'/app');const mobile=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth+1,targets:[...document.querySelectorAll('.wb-topbar [data-theme-option],.prompt-card-head button')].filter(e=>e.getClientRects().length&&getComputedStyle(e).visibility!=='hidden').map(e=>({name:e.getAttribute('aria-label'),width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height}))}));assert(!mobile.overflow);assert(mobile.targets.every(t=>t.width>=44&&t.height>=44));results.push('375px top bar and prompt targets');
 assert.deepEqual(errors,[]);fs.writeFileSync('design/mature/evidence/glass-2-direction.json',JSON.stringify({passed:true,results,mobile,errors},null,2));console.log(results.join('\n'));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
